### PR TITLE
Upgrade mysql-provider versions to 1.3.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by palfrey**
This should fix the build

### CODE REVIEW

**Comment by palfrey** [comment]
Not seeing a successful build status here, but Travis appears to be fine. See https://travis-ci.org/github/kislayverma/Rulette/builds/671265553

**Comment by kislayverma** [comment]
Thanks for the PR Tom. The build is fixed after the merge. I'd love to Jam
on how you are using Rulette and what more we can build together.

-Cheers!

**Comment by palfrey** [comment]
TBH, I'm not using it yet. I have an [old project](https://tevps.net/blog/2016/4/30/herder-automagic-scheduling-of-a-convention/) I might eventually pick up again that uses Optaplanner and Drools and I was idly wondering if this might work better for my use case and saw the build issue.

**Comment by kislayverma** [comment]
Got it. Let me know if you come across things you like or dislike - good to
hear from someone who is evaluating :)

Best of Luck!

-Kislay

**Pull request merged**
