### PR TITLE
Fail rule engine instantiation if conflicting rules exist.

### LINKED ISSUE #61: Adding conflicting rules does not fail rule engine instantiation
Found this issue by #59

### PR DESCRIPTION
**Pull request by calvincodes**
Fixes #61

### CODE REVIEW

**Comment by calvincodes** [comment]
@kislayverma Requesting review.

**Comment by calvincodes** [comment]
> Should we create a specific "ConflictingRuleDetected" exception for this? My earlier mistake of simply throwing "Exception" is making further development on top of this very difficult so let's do better this time.
> 
> Also, can we add a unit test for this

Sure. Makes sense. I kinda followed the legacy here and threw RuntimeException as I found at other places 😛 
Will make changes and update here.

**Comment by kislayverma** [comment]
I have created to track the matter of exception comprehensively -  https://github.com/kislayverma/Rulette/issues/64

**Comment by calvincodes** [comment]
@kislayverma Rebased with upstream. Ready for review. Also replaced one more usage of `RuntimeException` with `RuleConflictException`.

**Pull request merged**
